# Generated by Django 4.2.9 on 2024-01-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("tax_identification_number", models.CharField(max_length=50)),
                ("fiscal_year_start_date", models.DateField()),
            ],
            options={
                "permissions": [
                    ("add_companyinfo", "Can add company information"),
                    ("change_companyinfo", "Can change company information"),
                    ("delete_companyinfo", "Can delete company information"),
                    ("view_companyinfo", "Can view company information"),
                ],
            },
        ),
    ]
